services:
  postgres:
    build:
      context: .
      target: postgres

    container_name: postgres-postgis-pgvector

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb

    ports:
      - "5442:5432"

  django:
    build:
      context: .
      target: django

    container_name: django-app

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    depends_on:
      - postgres