# Generated by Django 6.0.6 on 2026-06-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0002_remove_propertyimage_url_alter_propertyimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
