# Generated by Django 6.0.6 on 2026-06-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0003_rename_name_property_title_property_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='city',
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
