# Generated by Django 6.0.6 on 2026-06-23 05:44

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0004_remove_location_city_alter_property_price_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='location',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['name_embedding'], m=16, name='location_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
